### ISSUE TITLE
Use release version of ajax-tags plugin

### ISSUE THREAD

**Issue by pradtke** [vahidhedayati/modaldynamix#1]
There is a release of ajax-tags. The current version of modaldynamix causes trouble for our build rules since it includes a snapshot release of ajax-tags. Please update to a release version.

https://bintray.com/grails/plugins/ajax-tags/1.0.0/view

**Comment by vahidhedayati** [comment]
Please try 1.0.2 of this plugin

**Comment by pradtke** [comment]
Our build works. Thanks for the quick turnaround
